FROM node:23-alpine as builder

# Working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Start the application
CMD ["npm", "run", "start:dev"]