name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r . ubuntu@YOUR_EC2_IP:/home/ubuntu/app
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_IP "
            cd /home/ubuntu/app &&
            sudo docker-compose down &&
            sudo docker-compose up -d
          "
