name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull vahe1232/blogify-api:latest
      - name: Delete Old docker container
        run: sudo docker rm -f api || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name api vahe1232/blogify-api